// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UberEats.Models;

#nullable disable

namespace UberEats.Migrations
{
    [DbContext(typeof(UberContext))]
    partial class UberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("UberEats.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DriverID");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverID = 1,
                            Name = "Restaurent"
                        },
                        new
                        {
                            DriverID = 2,
                            Name = "Grocery"
                        },
                        new
                        {
                            DriverID = 3,
                            Name = "Alcohol"
                        },
                        new
                        {
                            DriverID = 4,
                            Name = "Convienience"
                        },
                        new
                        {
                            DriverID = 5,
                            Name = "Flower shop"
                        },
                        new
                        {
                            DriverID = 6,
                            Name = "Pet Store"
                        },
                        new
                        {
                            DriverID = 7,
                            Name = "retail"
                        });
                });

            modelBuilder.Entity("UberEats.Models.Partner", b =>
                {
                    b.Property<int>("PartnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BusinessPhone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartnerID");

                    b.HasIndex("DriverID");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            PartnerID = 1,
                            BusinessAddress = "Stratocaster",
                            BusinessEmail = "Stratocaster@gmail.com",
                            BusinessName = "strat",
                            BusinessPhone = 908876754,
                            DriverID = 1
                        },
                        new
                        {
                            PartnerID = 2,
                            BusinessAddress = "Gibson Les Paul",
                            BusinessEmail = "les_paul@gmail.com",
                            BusinessName = "les_paul",
                            BusinessPhone = 908876754,
                            DriverID = 1
                        },
                        new
                        {
                            PartnerID = 3,
                            BusinessAddress = "Gibson SG",
                            BusinessEmail = "sg@gmail.com",
                            BusinessName = "sg",
                            BusinessPhone = 908876754,
                            DriverID = 1
                        },
                        new
                        {
                            PartnerID = 4,
                            BusinessAddress = "Yamaha FG700S",
                            BusinessEmail = "fg700s@gmail.com",
                            BusinessName = "fg700s",
                            BusinessPhone = 908876754,
                            DriverID = 7
                        },
                        new
                        {
                            PartnerID = 5,
                            BusinessAddress = "Washburn D10S",
                            BusinessEmail = "washburn@gmail.com",
                            BusinessName = "washburn",
                            BusinessPhone = 908876754,
                            DriverID = 7
                        },
                        new
                        {
                            PartnerID = 6,
                            BusinessAddress = "Rodriguez Caballero 11",
                            BusinessEmail = "rodriguez@gmail.com",
                            BusinessName = "rodriguez",
                            BusinessPhone = 908876754,
                            DriverID = 4
                        },
                        new
                        {
                            PartnerID = 7,
                            BusinessAddress = "Fender Precision",
                            BusinessEmail = "precision@gmail.com",
                            BusinessName = "precision",
                            BusinessPhone = 908876754,
                            DriverID = 2
                        },
                        new
                        {
                            PartnerID = 8,
                            BusinessAddress = "Hofner Icon",
                            BusinessEmail = "hofner@gmail.com",
                            BusinessName = "hofner",
                            BusinessPhone = 908876754,
                            DriverID = 2
                        },
                        new
                        {
                            PartnerID = 9,
                            BusinessAddress = "Ludwig 5-piece Drum Set with Cymbals",
                            BusinessEmail = "ludwig@gmail.com",
                            BusinessName = "ludwig",
                            BusinessPhone = 908876754,
                            DriverID = 3
                        },
                        new
                        {
                            PartnerID = 10,
                            BusinessAddress = "Tama 5-Piece Drum Set with Cymbals",
                            BusinessEmail = "tama@gmail.com",
                            BusinessName = "tama",
                            BusinessPhone = 908876754,
                            DriverID = 3
                        });
                });

            modelBuilder.Entity("UberEats.Models.Partner", b =>
                {
                    b.HasOne("UberEats.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
